export const NETWORKS = {
  MAINNET: 'mainnet',
  TESTNET: 'testnet',
};

export const MESSAGE_EVENTS = {
  WINDOW_SIGN_AND_BROADCAST: 'SC_SIGN_AND_BROADCAST',
  EXT_SIGN_AND_BROADCAST: 'SC_SIGN_AND_BROADCAST',
};
